### ISSUE TITLE
ACTUAL_TOURS cannot be found.

### ISSUE THREAD

**Issue by LaNaGr** [heldstephan/jpt-amz#1]
After model_build.sh, when doing: "~/jpt-amz$ bash model_apply.sh", 
I received "ACTUAL_TOURS file or directory not found" error here:
./merge TSPLIB_1 TSPLIB_2 TSPLIB

output:
amz0000: 133362 138653 <
amz0001: 140408 141812 <
amz0002: 149573 152769 <
amz0003: 115233 116385 <
amz0004: 158977 161045 <
amz0005: 133344 134697 <
amz0006: 125008 126258 <
amz0007: 122675 123901 <
amz0008: 107644 113424 <
amz0009: 80436 81240 <
amz0010: 118946 120135 <
amz0011: 129976 131275 <
amz0012: 158508 160093 <
Directory ACTUAL_TOURS does not exist

I think it happened in the line 38 of merge: "./score  result". I have still no idea how to fix it. Would you please give me any help? Thanks.

**Comment by heldstephan** [comment]
The ACTUAL_TOURS directory is only needed for fast internal scoring (outside the contest docker).
Commenting out that line from merge would be OK.
I will  provide a fix that will avoid internal scoring if the dir is not present and print instructions to create that dir.

**Comment by heldstephan** [comment]
Fixed with dc4ebc0aa091d4d1eb7dc7d9b9b2d8f8c19664ce.
